services:
  go-server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=munke
      - DB_PASSWORD=zocket
      - DB_NAME=zocket
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: munke
      POSTGRES_PASSWORD: zocket
      POSTGRES_DB: zocket
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data: